package NoUsados;

import Conectar.ConexionBaseDatos;
import Negocio.ConsultaBaseDatos;
import Negocio.Tabla;
import Vista.JFMenu;
import java.awt.Image;
import java.awt.Toolkit;
//import Negocio.ConsultaMySQL;
import java.sql.Connection;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
//import java.time.LocalDate;
//import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author G3
 */
public class JFLibroNOReal extends javax.swing.JFrame {

    ConexionBaseDatos con = new ConexionBaseDatos();
    Connection cn;
    ConsultaBaseDatos consulta;
    Tabla metodoTabla;
    DefaultTableModel tabla;
    JFMenu jfMenu;
    SimpleDateFormat formato;
    Date fecha;
    
    public JFLibroNOReal() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            cn = con.conexion();
        } catch (SQLException ex) {
            Logger.getLogger(JFLibroNOReal.class.getName()).log(Level.SEVERE, null, ex);
        }
        consulta = new ConsultaBaseDatos();
        tabla = (DefaultTableModel) this.jTlistaEstudiantes.getModel();
        metodoTabla = new Tabla();
        this.metodoTabla.actualizarTablaEstudiante(cn, tabla);
        BGfiltrar.add(jRBidEstudiante);
        BGfiltrar.add(jRBnombreEstudiante);
        this.JTFidEstudianteModificar.setEditable(false);
        this.limpiarCeldasRegistrar();
        this.jDCfechaNacimientoEstudiante.setEnabled(true);
        formato = new SimpleDateFormat("yyyy-MM-dddd");
    }

    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/EstudianteIcon2.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGfiltrar = new javax.swing.ButtonGroup();
        jTPestudiante = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFnombreEstudiante = new javax.swing.JTextField();
        jTFidEstudiante = new javax.swing.JTextField();
        jDCfechaNacimientoEstudiante = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jBregistrar = new javax.swing.JButton();
        jBnuevoRegistrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jRBidEstudiante = new javax.swing.JRadioButton();
        jRBnombreEstudiante = new javax.swing.JRadioButton();
        jTFfiltrarEstudiante = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTFidEstudianteModificar = new javax.swing.JTextField();
        jTFnombreEstudianteModificar = new javax.swing.JTextField();
        jDCfechaNacimientoEstudianteModificar = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jBactualizarDatos = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jBnuevoActualizar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTlistaEstudiantes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnuvolverAlMenu = new javax.swing.JMenuItem();
        jMnusalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estudiantes");
        setIconImage(getIconImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre y Apellido:");

        jLabel3.setText("Fecha de Nacimiento:");

        jDCfechaNacimientoEstudiante.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTFnombreEstudiante, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFidEstudiante, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDCfechaNacimientoEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFidEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFnombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDCfechaNacimientoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBregistrar.setText("Registrar Estudiante");
        jBregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarActionPerformed(evt);
            }
        });

        jBnuevoRegistrar.setText("Agregar un Nuevo Estudiante");
        jBnuevoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jBregistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jBnuevoRegistrar)
                .addGap(41, 41, 41))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBregistrar)
                    .addComponent(jBnuevoRegistrar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTPestudiante.addTab("Registrar Libro", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar"));

        jRBidEstudiante.setText("ID Estudiante");

        jRBnombreEstudiante.setText("Nombre");

        jTFfiltrarEstudiante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFfiltrarEstudianteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jRBidEstudiante)
                .addGap(23, 23, 23)
                .addComponent(jRBnombreEstudiante)
                .addGap(18, 18, 18)
                .addComponent(jTFfiltrarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBidEstudiante)
                    .addComponent(jRBnombreEstudiante)
                    .addComponent(jTFfiltrarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevos Datos"));

        jLabel4.setText("ID:");

        jLabel5.setText("Nombre y Apellido:");

        jLabel6.setText("Fecha de Nacimiento:");

        jDCfechaNacimientoEstudianteModificar.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTFnombreEstudianteModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(JTFidEstudianteModificar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDCfechaNacimientoEstudianteModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFidEstudianteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFnombreEstudianteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jDCfechaNacimientoEstudianteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBactualizarDatos.setText("Actualizar Datos");
        jBactualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarDatosActionPerformed(evt);
            }
        });

        jBeliminar.setText("Eliminar Estudiante");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });

        jBnuevoActualizar.setText("Nuevo");
        jBnuevoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBeliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBactualizarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBnuevoActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBactualizarDatos)
                .addGap(18, 18, 18)
                .addComponent(jBeliminar)
                .addGap(18, 18, 18)
                .addComponent(jBnuevoActualizar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jTPestudiante.addTab("Modificar Datos", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Estudiantes"));

        jTlistaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idEstudiante", "NombreEstudiante", "FechaNacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTlistaEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTlistaEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTlistaEstudiantes);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        jMenu1.setText("File");

        jMnuvolverAlMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuvolverAlMenu.setText("Volver al Menú");
        jMnuvolverAlMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuvolverAlMenuActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuvolverAlMenu);

        jMnusalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMnusalir.setText("Salir");
        jMnusalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnusalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMnusalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTPestudiante)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTPestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    private void jBregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarActionPerformed
//        String idEstudiante = this.jTFidEstudiante.getText();
//        String nombreEstudiante = this.jTFnombreEstudiante.getText();
//        String fechaNacimientoEstudiante = this.jTFfechaNacimientoEstudiante.getText();
//        
//        this.consulta.registrarEstudiante(cn, idEstudiante, nombreEstudiante, fechaNacimientoEstudiante);
//        this.metodoTabla.actualizarTablaEstudiante(cn, tabla);
//        this.jTlistaEstudiantes.setModel(tabla);
//        this.jTFidEstudiante.setEditable(false);
//        this.jTFnombreEstudiante.setEditable(false);
//        this.jTFfechaNacimientoEstudiante.setEditable(false);

        String idEstudiante = this.jTFidEstudiante.getText();
        String nombreEstudiante = this.jTFnombreEstudiante.getText();
        String fechaNacimientoEstudiante = this.formato.format(this.jDCfechaNacimientoEstudiante.getDate());
        
        if(this.consulta.registrarEstudiante(cn, idEstudiante, nombreEstudiante, fechaNacimientoEstudiante) == true){
            this.limpiarCeldasRegistrar();
            this.jTFidEstudiante.requestFocus();
        }
        else{
            this.metodoTabla.actualizarTablaEstudiante(cn, tabla);
            this.jTlistaEstudiantes.setModel(tabla);
            this.jTFidEstudiante.setEditable(false);
            this.jTFnombreEstudiante.setEditable(false);
            this.jDCfechaNacimientoEstudiante.setEnabled(false);
        }
    }//GEN-LAST:event_jBregistrarActionPerformed

    private void jBnuevoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoRegistrarActionPerformed
//        this.jTFidEstudiante.setEditable(true);
//        this.jTFnombreEstudiante.setEditable(true);
//        this.jDCfechaNacimientoEstudiante.setEnabled(true);
//        this.jTFidEstudiante.setText("");
//        this.jTFnombreEstudiante.setText("");
//        this.jDCfechaNacimientoEstudiante.setDate(null);
        this.limpiarCeldasRegistrar();
        this.jTFidEstudiante.requestFocus();
    }//GEN-LAST:event_jBnuevoRegistrarActionPerformed

    private void limpiarCeldasRegistrar(){
        this.jTFidEstudiante.setEditable(true);
        this.jTFnombreEstudiante.setEditable(true);
        this.jDCfechaNacimientoEstudiante.setEnabled(true);
        this.jTFidEstudiante.setText("");
        this.jTFnombreEstudiante.setText("");
        this.jDCfechaNacimientoEstudiante.setDate(null); //OJO
    }
    
    private void jTFfiltrarEstudianteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFfiltrarEstudianteKeyReleased
        if(this.jRBidEstudiante.isSelected()){
            this.metodoTabla.consultarEstudiante(cn, "idEstudiante", this.jTFfiltrarEstudiante.getText(), tabla);
        }
        else if(this.jRBnombreEstudiante.isSelected()){
            this.metodoTabla.consultarEstudiante(cn, "NombreEstudiante", this.jTFfiltrarEstudiante.getText(), tabla);
        }
        else{
            JOptionPane.showMessageDialog(null, "Elija un atributo para filtrar.", "Error", JOptionPane.ERROR_MESSAGE);
            this.jTFfiltrarEstudiante.setText("");
        }
    }//GEN-LAST:event_jTFfiltrarEstudianteKeyReleased

    private void jTlistaEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTlistaEstudiantesMouseClicked
        if(this.jTPestudiante.getSelectedIndex() == 1){
            int fila = this.jTlistaEstudiantes.getSelectedRow();
            String id = tabla.getValueAt(fila, 0).toString();
            String nombre = tabla.getValueAt(fila, 1).toString();
            String fechaNacimiento = tabla.getValueAt(fila, 2).toString();
            
            this.JTFidEstudianteModificar.setText(id);
            this.jTFnombreEstudianteModificar.setText(nombre);
//            this.jTFfechaNacimientoEstudianteModificar.setText(fechaNacimiento);
            try {
                fecha = formato.parse(fechaNacimiento);
            } catch (ParseException ex) {
                Logger.getLogger(JFLibroNOReal.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDCfechaNacimientoEstudianteModificar.setDate(fecha);
            
        }
    }//GEN-LAST:event_jTlistaEstudiantesMouseClicked

    private void jBactualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactualizarDatosActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "Está seguro de actualizar los datos...?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(opcion == JOptionPane.YES_OPTION){
            String idEstudiante = this.JTFidEstudianteModificar.getText();
            String nombreActualizado = this.jTFnombreEstudianteModificar.getText();
//            String fechaActualizada = this.jTFfechaNacimientoEstudianteModificar.getText();
            String fechaActualizada = this.formato.format(this.jDCfechaNacimientoEstudianteModificar.getDate());

            this.consulta.actualizarEstudiante(cn, idEstudiante, nombreActualizado, fechaActualizada);
            this.metodoTabla.actualizarTablaEstudiante(cn, tabla);
            this.jTlistaEstudiantes.setModel(tabla);

            this.jTFfiltrarEstudiante.setText("");     
//            this.jTFidEstudiante.setText("");
//            this.jTFnombreEstudiante.setText("");
//            this.jTFfechaNacimientoEstudiante.setText("");
            this.limpiarCeldasRegistrar();
        }
    }//GEN-LAST:event_jBactualizarDatosActionPerformed

    private void jBnuevoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActualizarActionPerformed
        this.BGfiltrar.clearSelection();
        this.JTFidEstudianteModificar.setText("");
        this.jTFnombreEstudianteModificar.setText("");
        this.jDCfechaNacimientoEstudianteModificar.setDate(null);
//        this.jTFfechaNacimientoEstudianteModificar.setText("");
        this.jTFfiltrarEstudiante.setText("");
    }//GEN-LAST:event_jBnuevoActualizarActionPerformed
 
    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        String id = this.JTFidEstudianteModificar.getText();
        
        int opcion = JOptionPane.showConfirmDialog(null, "Está seguro de eliminar al estudiante...?", "Eliminar Estudiante", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(opcion == JOptionPane.YES_OPTION){
            this.consulta.eliminarEstudiante(cn, id);
            this.metodoTabla.actualizarTablaEstudiante(cn, tabla);
            this.jTlistaEstudiantes.setModel(tabla);
            
            this.JTFidEstudianteModificar.setText("");
            this.jTFnombreEstudianteModificar.setText("");
//            this.jTFfechaNacimientoEstudianteModificar.setText("");
            this.jDCfechaNacimientoEstudianteModificar.setDate(null);
            
            this.jTFfiltrarEstudiante.setText("");
            this.limpiarCeldasRegistrar();
//            this.jTFidEstudiante.setText("");
//            this.jTFnombreEstudiante.setText("");
//            this.jTFfechaNacimientoEstudiante.setText("");
        }
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jMnuvolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuvolverAlMenuActionPerformed
        jfMenu = new JFMenu();
        jfMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMnuvolverAlMenuActionPerformed

    private void jMnusalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnusalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMnusalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLibroNOReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLibroNOReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLibroNOReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLibroNOReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLibroNOReal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGfiltrar;
    private javax.swing.JTextField JTFidEstudianteModificar;
    private javax.swing.JButton jBactualizarDatos;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBnuevoActualizar;
    private javax.swing.JButton jBnuevoRegistrar;
    private javax.swing.JButton jBregistrar;
    private com.toedter.calendar.JDateChooser jDCfechaNacimientoEstudiante;
    private com.toedter.calendar.JDateChooser jDCfechaNacimientoEstudianteModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnusalir;
    private javax.swing.JMenuItem jMnuvolverAlMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRBidEstudiante;
    private javax.swing.JRadioButton jRBnombreEstudiante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFfiltrarEstudiante;
    private javax.swing.JTextField jTFidEstudiante;
    private javax.swing.JTextField jTFnombreEstudiante;
    private javax.swing.JTextField jTFnombreEstudianteModificar;
    private javax.swing.JTabbedPane jTPestudiante;
    private javax.swing.JTable jTlistaEstudiantes;
    // End of variables declaration//GEN-END:variables
}
