package Vista;

import Conectar.ConexionBaseDatos;
import Negocio.ConsultaBaseDatos;
import Negocio.Tabla;
import java.awt.Image;
import java.awt.Toolkit;
//import Negocio.ConsultaMySQL;
import java.sql.Connection;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
//import java.time.LocalDate;
//import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer123
 */
public class JFAutorReal extends javax.swing.JFrame {

    ConexionBaseDatos con = new ConexionBaseDatos();
    Connection cn;
    ConsultaBaseDatos consulta;
    Tabla metodoTabla;
    DefaultTableModel tablaAutor;
    JFMenu jfMenu;
    SimpleDateFormat formatoFecha;
    Date fecha;
    Calendar cal = Calendar.getInstance();

    
    public JFAutorReal() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            cn = con.conexion();
        } catch (SQLException ex) {
            Logger.getLogger(JFAutorReal.class.getName()).log(Level.SEVERE, null, ex);
        }
        consulta = new ConsultaBaseDatos();
        tablaAutor = (DefaultTableModel) this.jTlistaAutores.getModel();
        metodoTabla = new Tabla();
        this.metodoTabla.actualizarTablaAutor(cn, tablaAutor);
        BGfiltrar.add(jRBidAutor);
        BGfiltrar.add(jRBnombreAutor);
        this.JTFidAutorModificar.setEditable(false);
        this.limpiarCeldasRegistrar();
//        this.jDCfechaNacimientoAutor.setEnabled(true); //QUE HACE
        this.jDCfechaNacimientoAutor.setMaxSelectableDate(cal.getTime());
        this.jDCfechaNacimientoAutorModificar.setMaxSelectableDate(cal.getTime());
        formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
    }

    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/AutorIcon.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGfiltrar = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jTPautor = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFnombreAutor = new javax.swing.JTextField();
        jTFidAutor = new javax.swing.JTextField();
        jDCfechaNacimientoAutor = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jBregistrarAutor = new javax.swing.JButton();
        jBnuevoRegistrarAutor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jRBidAutor = new javax.swing.JRadioButton();
        jRBnombreAutor = new javax.swing.JRadioButton();
        jTFfiltrarAutor = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTFidAutorModificar = new javax.swing.JTextField();
        jTFnombreAutorModificar = new javax.swing.JTextField();
        jDCfechaNacimientoAutorModificar = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jBactualizarDatosAutor = new javax.swing.JButton();
        jBeliminarAutor = new javax.swing.JButton();
        jBnuevoModificarAutor = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTlistaAutores = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnuvolverAlMenu = new javax.swing.JMenuItem();
        jMnusalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autores");
        setIconImage(getIconImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre y Apellido:");

        jLabel3.setText("Fecha de Nacimiento:");

        jTFnombreAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFnombreAutorKeyTyped(evt);
            }
        });

        jTFidAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFidAutorKeyTyped(evt);
            }
        });

        jDCfechaNacimientoAutor.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTFnombreAutor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFidAutor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDCfechaNacimientoAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFidAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFnombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDCfechaNacimientoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBregistrarAutor.setText("Registrar Autor");
        jBregistrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarAutorActionPerformed(evt);
            }
        });

        jBnuevoRegistrarAutor.setText("Agregar un Nuevo Autor");
        jBnuevoRegistrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoRegistrarAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jBregistrarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jBnuevoRegistrarAutor)
                .addGap(48, 48, 48))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBregistrarAutor)
                    .addComponent(jBnuevoRegistrarAutor))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTPautor.addTab("Registrar Autor", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar"));

        jRBidAutor.setText("ID Autor");

        jRBnombreAutor.setText("Nombre");

        jTFfiltrarAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFfiltrarAutorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFfiltrarAutorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jRBidAutor)
                .addGap(23, 23, 23)
                .addComponent(jRBnombreAutor)
                .addGap(18, 18, 18)
                .addComponent(jTFfiltrarAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBidAutor)
                    .addComponent(jRBnombreAutor)
                    .addComponent(jTFfiltrarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevos Datos"));

        jLabel4.setText("ID:");

        jLabel5.setText("Nombre y Apellido:");

        jLabel6.setText("Fecha de Nacimiento:");

        jTFnombreAutorModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFnombreAutorModificarKeyTyped(evt);
            }
        });

        jDCfechaNacimientoAutorModificar.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTFnombreAutorModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(JTFidAutorModificar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDCfechaNacimientoAutorModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFidAutorModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFnombreAutorModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jDCfechaNacimientoAutorModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBactualizarDatosAutor.setText("Actualizar Datos");
        jBactualizarDatosAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarDatosAutorActionPerformed(evt);
            }
        });

        jBeliminarAutor.setText("Eliminar Autor");
        jBeliminarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarAutorActionPerformed(evt);
            }
        });

        jBnuevoModificarAutor.setText("Nuevo");
        jBnuevoModificarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoModificarAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBactualizarDatosAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBeliminarAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBnuevoModificarAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBactualizarDatosAutor)
                .addGap(18, 18, 18)
                .addComponent(jBeliminarAutor)
                .addGap(18, 18, 18)
                .addComponent(jBnuevoModificarAutor)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTPautor.addTab("Modificar Datos del Autor", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Autores"));

        jTlistaAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idAutor", "NombreAutor", "FechaNacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTlistaAutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTlistaAutoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTlistaAutores);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        jMenu1.setText("File");

        jMnuvolverAlMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuvolverAlMenu.setText("Volver al Menú");
        jMnuvolverAlMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuvolverAlMenuActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuvolverAlMenu);

        jMnusalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMnusalir.setText("Salir");
        jMnusalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnusalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMnusalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTPautor)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTPautor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    private void jBregistrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarAutorActionPerformed
        String idAutor = this.jTFidAutor.getText();
        String nombreAutor = this.jTFnombreAutor.getText();
        String fechaNacimientoAutor = "";
        if (this.jDCfechaNacimientoAutor.getDate() != null) {
            fechaNacimientoAutor = this.formatoFecha.format(this.jDCfechaNacimientoAutor.getDate());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fecha de nacimiento.", "Error", JOptionPane.ERROR_MESSAGE);
            this.jDCfechaNacimientoAutor.setDate(null);
        }
        
        if(idAutor.isEmpty() || nombreAutor.isEmpty() || this.jDCfechaNacimientoAutor.getDate() == null){
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos antes de registrar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(this.consulta.registrarAutor(cn, idAutor, nombreAutor, fechaNacimientoAutor) == true){
                this.limpiarCeldasRegistrar();
                this.jTFidAutor.requestFocus();
            }
            else{
                this.metodoTabla.actualizarTablaAutor(cn, tablaAutor);
                this.jTlistaAutores.setModel(tablaAutor);
                this.jTFidAutor.setEditable(false);
                this.jTFnombreAutor.setEditable(false);
                this.jDCfechaNacimientoAutor.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jBregistrarAutorActionPerformed

    private void jBnuevoRegistrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoRegistrarAutorActionPerformed
        this.limpiarCeldasRegistrar();
        this.jTFidAutor.requestFocus();
    }//GEN-LAST:event_jBnuevoRegistrarAutorActionPerformed

    private void limpiarCeldasRegistrar(){
        this.jTFidAutor.setEditable(true);
        this.jTFnombreAutor.setEditable(true);
        this.jDCfechaNacimientoAutor.setEnabled(true);
        this.jTFidAutor.setText("");
        this.jTFnombreAutor.setText("");
        this.jDCfechaNacimientoAutor.setDate(null);
    }
    
    private void jTFfiltrarAutorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFfiltrarAutorKeyReleased
        if(this.jRBidAutor.isSelected()){
            this.metodoTabla.consultarAutor(cn, "idAutor", this.jTFfiltrarAutor.getText(), tablaAutor);
        }
        else if(this.jRBnombreAutor.isSelected()){
            this.metodoTabla.consultarAutor(cn, "NombreAutor", this.jTFfiltrarAutor.getText(), tablaAutor);
        }
        else{
            JOptionPane.showMessageDialog(null, "Elija un atributo para filtrar.", "Error", JOptionPane.ERROR_MESSAGE);
            this.jTFfiltrarAutor.setText("");
        }
    }//GEN-LAST:event_jTFfiltrarAutorKeyReleased

    private void jTlistaAutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTlistaAutoresMouseClicked
        if(this.jTPautor.getSelectedIndex() == 1){
            int fila = this.jTlistaAutores.getSelectedRow();
            String id = tablaAutor.getValueAt(fila, 0).toString();
            String nombre = tablaAutor.getValueAt(fila, 1).toString();
            String fechaNacimiento = tablaAutor.getValueAt(fila, 2).toString();
            
            this.JTFidAutorModificar.setText(id);
            this.jTFnombreAutorModificar.setText(nombre);
//            this.jTFfechaNacimientoAutorModificar.setText(fecha);
            try {
                fecha = formatoFecha.parse(fechaNacimiento);
            } catch (ParseException ex) {
                Logger.getLogger(JFAutorReal.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDCfechaNacimientoAutorModificar.setDate(fecha);
        }
    }//GEN-LAST:event_jTlistaAutoresMouseClicked

    private void jBactualizarDatosAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactualizarDatosAutorActionPerformed
        String idAutor = this.JTFidAutorModificar.getText();
        String nombreActualizado = this.jTFnombreAutorModificar.getText();
        String fechaActualizada = this.formatoFecha.format(this.jDCfechaNacimientoAutorModificar.getDate());
        
        if(nombreActualizado.isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos antes de actualizar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
            this.jTFnombreAutorModificar.requestFocus();           
        }
        else{
            int opcion = JOptionPane.showConfirmDialog(null, "Está seguro de actualizar los datos...?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(opcion == JOptionPane.YES_OPTION){
                this.consulta.actualizarAutor(cn, idAutor, nombreActualizado, fechaActualizada);
                this.metodoTabla.actualizarTablaAutor(cn, tablaAutor);
                this.jTlistaAutores.setModel(tablaAutor);

                this.jTFfiltrarAutor.setText("");     
                this.limpiarCeldasRegistrar();
            }
        }
    }//GEN-LAST:event_jBactualizarDatosAutorActionPerformed

    private void jBnuevoModificarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoModificarAutorActionPerformed
        this.BGfiltrar.clearSelection();
        this.JTFidAutorModificar.setText("");
        this.jTFnombreAutorModificar.setText("");
        this.jDCfechaNacimientoAutorModificar.setDate(null);
        this.jTFfiltrarAutor.setText("");
        this.metodoTabla.actualizarTablaAutor(cn, tablaAutor);
        this.jTlistaAutores.setModel(tablaAutor); // OJOJOJO
    }//GEN-LAST:event_jBnuevoModificarAutorActionPerformed
 
    private void jBeliminarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarAutorActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "Está seguro de eliminar al autor...?\nTambién se eliminarán los libros asociados a él.", "Eliminar autor", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(opcion == JOptionPane.YES_OPTION){
            String idAutor = this.JTFidAutorModificar.getText();
            this.consulta.eliminarAutor(cn, idAutor);
            this.metodoTabla.actualizarTablaAutor(cn, tablaAutor);
            this.jTlistaAutores.setModel(tablaAutor);
            
            this.JTFidAutorModificar.setText("");
            this.jTFnombreAutorModificar.setText("");
            this.jDCfechaNacimientoAutorModificar.setDate(null);
            this.BGfiltrar.clearSelection();
            this.jTFfiltrarAutor.setText("");
            this.limpiarCeldasRegistrar();           
        }
    }//GEN-LAST:event_jBeliminarAutorActionPerformed

    private void jMnuvolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuvolverAlMenuActionPerformed
        jfMenu = new JFMenu();
        jfMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMnuvolverAlMenuActionPerformed

    private void jMnusalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnusalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMnusalirActionPerformed

    private void jTFidAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFidAutorKeyTyped
        char caracter = evt.getKeyChar(); 
        if(Character.isLetter(caracter)){ 
            evt.consume(); //ya no lo va a usar y borra el caracter 
            JOptionPane.showMessageDialog(null, "Ingrese solamente números.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
        } 
    }//GEN-LAST:event_jTFidAutorKeyTyped

    private void jTFnombreAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnombreAutorKeyTyped
        char caracter = evt.getKeyChar(); 
        if(Character.isDigit(caracter)){ 
            evt.consume(); //ya no lo va a usar y borra el caracter 
            JOptionPane.showMessageDialog(null, "Ingrese solamente letras.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
        }      
    }//GEN-LAST:event_jTFnombreAutorKeyTyped

    private void jTFnombreAutorModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnombreAutorModificarKeyTyped
        char caracter = evt.getKeyChar(); 
        if(Character.isDigit(caracter)){ 
            evt.consume(); //ya no lo va a usar y borra el caracter 
            JOptionPane.showMessageDialog(null, "Ingrese solamente letras.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
        }
    }//GEN-LAST:event_jTFnombreAutorModificarKeyTyped

    private void jTFfiltrarAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFfiltrarAutorKeyTyped
        if(this.jRBidAutor.isSelected()){
            char caracter = evt.getKeyChar(); 
            if(Character.isLetter(caracter)){ 
                evt.consume(); //ya no lo va a usar y borra el caracter 
                JOptionPane.showMessageDialog(null, "Ingrese solamente números.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
            } 
        }
        else if(this.jRBnombreAutor.isSelected()){
            char caracter = evt.getKeyChar(); 
            if(Character.isDigit(caracter)){ 
                evt.consume(); //ya no lo va a usar y borra el caracter 
                JOptionPane.showMessageDialog(null, "Ingrese solamente letras.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
            }            
        }        
    }//GEN-LAST:event_jTFfiltrarAutorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAutorReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAutorReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAutorReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAutorReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAutorReal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGfiltrar;
    private javax.swing.JTextField JTFidAutorModificar;
    private javax.swing.JButton jBactualizarDatosAutor;
    private javax.swing.JButton jBeliminarAutor;
    private javax.swing.JButton jBnuevoModificarAutor;
    private javax.swing.JButton jBnuevoRegistrarAutor;
    private javax.swing.JButton jBregistrarAutor;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDCfechaNacimientoAutor;
    private com.toedter.calendar.JDateChooser jDCfechaNacimientoAutorModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnusalir;
    private javax.swing.JMenuItem jMnuvolverAlMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRBidAutor;
    private javax.swing.JRadioButton jRBnombreAutor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFfiltrarAutor;
    private javax.swing.JTextField jTFidAutor;
    private javax.swing.JTextField jTFnombreAutor;
    private javax.swing.JTextField jTFnombreAutorModificar;
    private javax.swing.JTabbedPane jTPautor;
    private javax.swing.JTable jTlistaAutores;
    // End of variables declaration//GEN-END:variables
}
