package Vista;

import Vista.*;
import Conectar.ConexionBaseDatos;
import Negocio.ConsultaBaseDatos;
import Negocio.Tabla;
import java.awt.Image;
import java.awt.Toolkit;
//import Negocio.ConsultaMySQL;
import java.sql.Connection;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
//import java.time.LocalDate;
//import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer123
 */
public class JFLibroSinIDyAnioPetado extends javax.swing.JFrame {

    ConexionBaseDatos con = new ConexionBaseDatos();
    Connection cn;
    ConsultaBaseDatos consulta;
    Tabla metodoTabla;
    DefaultTableModel tablaLibro, tablaAutor;
    JFMenu jfMenu;
    SimpleDateFormat formatoFecha;
    Date fecha;
    
    public JFLibroSinIDyAnioPetado() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            cn = con.conexion();
        } catch (SQLException ex) {
            Logger.getLogger(JFLibroSinIDyAnioPetado.class.getName()).log(Level.SEVERE, null, ex);
        }
        consulta = new ConsultaBaseDatos();
        tablaLibro = (DefaultTableModel) this.jTlistalibros.getModel();
        tablaAutor = (DefaultTableModel) this.jTlistaAutores.getModel();
        metodoTabla = new Tabla();
//        this.metodoTabla.actualizarTablaLibro(cn, tablaLibro);
        this.metodoTabla.actualizarTablaLibro2(cn, tablaLibro);

        this.metodoTabla.actualizarTablaAutor(cn, tablaAutor);
        BGfiltrar.add(jRBidLibro);
        BGfiltrar.add(jRBtituloLibro);
        this.JTFidLibroModificar.setEditable(false);
        this.jTFidAutorModificar.setEditable(false);
        this.limpiarCeldasRegistrar();
        this.jDCfechaNacimientoAutor.setEnabled(true);
        formatoFecha = new SimpleDateFormat("yyyy-MM-dd"); ///OJOOOO  
    }

    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/LibroIcon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGfiltrar = new javax.swing.ButtonGroup();
        jTPlibro = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFtituloLibro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFstockLibro = new javax.swing.JTextField();
        jDCanioPublicacionLibro = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jBregistrarLibro = new javax.swing.JButton();
        jBnuevoRegistrarLibro = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTFidAutor = new javax.swing.JTextField();
        jTFnombreAutor = new javax.swing.JTextField();
        jDCfechaNacimientoAutor = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jRBidLibro = new javax.swing.JRadioButton();
        jRBtituloLibro = new javax.swing.JRadioButton();
        jTFfiltrarLibro = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTFidLibroModificar = new javax.swing.JTextField();
        jTFtituloLibroModificar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFstockLibroModificar = new javax.swing.JTextField();
        jDCfechaPublicacionLibroModificar = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jTFidAutorModificar = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jBactualizarDatosLibro = new javax.swing.JButton();
        jBeliminarLibro = new javax.swing.JButton();
        jBnuevoModificarLibro = new javax.swing.JButton();
        jPAutores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTlistaAutores = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTlistalibros = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnuvolverAlMenu = new javax.swing.JMenuItem();
        jMnusalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libros");
        setIconImage(getIconImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Libro"));

        jLabel2.setText("Título:");

        jLabel3.setText("Año de Publicación:");

        jLabel7.setText("Stock:");

        jTFstockLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFstockLibroKeyTyped(evt);
            }
        });

        jDCanioPublicacionLibro.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFtituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jDCanioPublicacionLibro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFstockLibro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFtituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDCanioPublicacionLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFstockLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBregistrarLibro.setText("Registrar Libro");
        jBregistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarLibroActionPerformed(evt);
            }
        });

        jBnuevoRegistrarLibro.setText("Agregar un Nuevo Libro");
        jBnuevoRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoRegistrarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jBregistrarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBnuevoRegistrarLibro)
                .addGap(24, 24, 24))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBregistrarLibro)
                    .addComponent(jBnuevoRegistrarLibro))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Autor"));

        jLabel12.setText("ID Autor:");

        jLabel13.setText("Nombre y Apellido:");

        jLabel14.setText("Fecha de Nacimiento:");

        jTFidAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFidAutorKeyTyped(evt);
            }
        });

        jTFnombreAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFnombreAutorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFnombreAutorKeyTyped(evt);
            }
        });

        jDCfechaNacimientoAutor.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFidAutor)
                    .addComponent(jTFnombreAutor)
                    .addComponent(jDCfechaNacimientoAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTFidAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTFnombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jDCfechaNacimientoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPlibro.addTab("Registrar Libro", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar"));

        jRBidLibro.setText("ID Libro");

        jRBtituloLibro.setText("Título");

        jTFfiltrarLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFfiltrarLibroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFfiltrarLibroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jRBidLibro)
                .addGap(23, 23, 23)
                .addComponent(jRBtituloLibro)
                .addGap(18, 18, 18)
                .addComponent(jTFfiltrarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBidLibro)
                    .addComponent(jRBtituloLibro)
                    .addComponent(jTFfiltrarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevos Datos"));

        jLabel4.setText("ID Libro:");

        jLabel5.setText("Título:");

        jLabel6.setText("Fecha de Publicación:");

        jLabel8.setText("Stock:");

        jDCfechaPublicacionLibroModificar.setDateFormatString("yyyy-MM-dd");

        jLabel9.setText("ID Autor:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(99, 99, 99))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(85, 85, 85)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(85, 85, 85)))
                        .addGap(56, 226, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDCfechaPublicacionLibroModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFtituloLibroModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFstockLibroModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFidAutorModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFidLibroModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFidLibroModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFtituloLibroModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTFidAutorModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jDCfechaPublicacionLibroModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTFstockLibroModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBactualizarDatosLibro.setText("Actualizar Datos");
        jBactualizarDatosLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarDatosLibroActionPerformed(evt);
            }
        });

        jBeliminarLibro.setText("Eliminar Libro");
        jBeliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarLibroActionPerformed(evt);
            }
        });

        jBnuevoModificarLibro.setText("Nuevo");
        jBnuevoModificarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoModificarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jBactualizarDatosLibro)
                .addGap(18, 18, 18)
                .addComponent(jBeliminarLibro)
                .addGap(18, 18, 18)
                .addComponent(jBnuevoModificarLibro)
                .addGap(16, 16, 16))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBactualizarDatosLibro)
                    .addComponent(jBeliminarLibro)
                    .addComponent(jBnuevoModificarLibro))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTPlibro.addTab("Modificar Datos del Libro", jPanel2);

        jPAutores.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Autores"));

        jTlistaAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idAutor", "NombreAutor", "FechaNacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTlistaAutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTlistaAutoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTlistaAutores);

        javax.swing.GroupLayout jPAutoresLayout = new javax.swing.GroupLayout(jPAutores);
        jPAutores.setLayout(jPAutoresLayout);
        jPAutoresLayout.setHorizontalGroup(
            jPAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAutoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPAutoresLayout.setVerticalGroup(
            jPAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAutoresLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Libros"));

        jTlistalibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idLibro", "Titulo", "idAutor", "AñoPublicacion", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTlistalibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTlistalibrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTlistalibros);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMnuvolverAlMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuvolverAlMenu.setText("Volver al Menú");
        jMnuvolverAlMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuvolverAlMenuActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuvolverAlMenu);

        jMnusalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMnusalir.setText("Salir");
        jMnusalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnusalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMnusalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTPlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTPlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    private void jBregistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarLibroActionPerformed
        String idAutor = this.jTFidAutor.getText();
        String nombreAutor = this.jTFnombreAutor.getText();
        String fechaNacimientoAutor = "";
//        String fechaNacimientoAutor = this.formatoFecha.format(this.jDCfechaNacimientoAutor.getDate());
//        String idLibro = this.jTFidLibro.getText();
        String titulo = this.jTFtituloLibro.getText();
        int anioPublicacion = 0;
        System.out.println(this.jDCanioPublicacionLibro.getDate().getYear() + 1900);
//        String anioPublicacion = this.formatoFecha.format(this.jDCfechaPublicacionLibro.getDate());
        String stock = this.jTFstockLibro.getText();
        if(this.jDCfechaNacimientoAutor.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fecha de nacimiento válida.", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        else if(this.jDCanioPublicacionLibro.getDate() == null){
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fecha de publicación válida.", "Error", JOptionPane.ERROR_MESSAGE);           
        }
        else{
            fechaNacimientoAutor = this.formatoFecha.format(this.jDCfechaNacimientoAutor.getDate());
//            fechaNacimientoAutor = this.jDCfechaNacimientoAutor.getDateFormatString();
//            anioPublicacion = this.formatoFecha.format(this.jDCanioPublicacionLibro.getDate());
            anioPublicacion = this.jDCanioPublicacionLibro.getDate().getYear() + 1900;

        } 
        
        if(idAutor.isEmpty() || nombreAutor.isEmpty() || titulo.isEmpty() || stock.isEmpty() ||
           this.jDCfechaNacimientoAutor.getDate() == null || this.jDCanioPublicacionLibro.getDate() == null){
                JOptionPane.showMessageDialog(null, "Por favor, corrige los campos antes de registrar.", "Error", JOptionPane.ERROR_MESSAGE);            
        }
        else{
            if(this.consulta.registrarLibro2(cn, titulo, idAutor, anioPublicacion, stock, nombreAutor, fechaNacimientoAutor) == true){
                this.limpiarCeldasRegistrar();
                this.jTFnombreAutor.requestFocus();
            }
            else{
                this.metodoTabla.actualizarTablaAutor(cn, tablaAutor);
                this.metodoTabla.actualizarTablaLibro2(cn, tablaLibro);
                this.jTlistalibros.setModel(tablaLibro);
                this.jTlistaAutores.setModel(tablaAutor);
                this.jTFidAutor.setEditable(false);
                this.jTFnombreAutor.setEditable(false);
                this.jDCfechaNacimientoAutor.setEnabled(false);
//                this.jTFidLibro.setEditable(false);
                this.jTFtituloLibro.setEditable(false);
                this.jDCanioPublicacionLibro.setEnabled(false);
                this.jTFstockLibro.setEditable(false);
            }
        }
    }//GEN-LAST:event_jBregistrarLibroActionPerformed

    private void jBnuevoRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoRegistrarLibroActionPerformed
        this.limpiarCeldasRegistrar();
        this.jTFnombreAutor.requestFocus();
        this.metodoTabla.actualizarTablaAutor(cn, tablaAutor);
        this.metodoTabla.actualizarTablaLibro(cn, tablaLibro);
        this.jTlistaAutores.setModel(tablaAutor);
        this.jTlistalibros.setModel(tablaLibro);
    }//GEN-LAST:event_jBnuevoRegistrarLibroActionPerformed

    private void limpiarCeldasRegistrar(){
        this.jTFidAutor.setEditable(true);
        this.jTFnombreAutor.setEditable(true);
        this.jDCfechaNacimientoAutor.setEnabled(true);
//        this.jTFidLibro.setEditable(true);
        this.jTFtituloLibro.setEditable(true);
        this.jDCanioPublicacionLibro.setEnabled(true);
        this.jTFstockLibro.setEditable(true);
        this.jTFidAutor.setText("");
        this.jTFnombreAutor.setText("");
        this.jDCfechaNacimientoAutor.setDate(null);
//        this.jTFidLibro.setText("");
        this.jTFtituloLibro.setText("");
        this.jDCanioPublicacionLibro.setDate(null);
        this.jTFstockLibro.setText("");
    }
    
    private void jTFfiltrarLibroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFfiltrarLibroKeyReleased
        if(this.jRBidLibro.isSelected()){
            this.metodoTabla.consultarLibro(cn, "idLibro", this.jTFfiltrarLibro.getText(), tablaLibro);
        }
        else if(this.jRBtituloLibro.isSelected()){
            this.metodoTabla.consultarLibro(cn, "Titulo", this.jTFfiltrarLibro.getText(), tablaLibro);

        }
        else{
            JOptionPane.showMessageDialog(null, "Elija un atributo para filtrar.", "Error", JOptionPane.ERROR_MESSAGE);
            this.jTFfiltrarLibro.setText("");
        }   
    }//GEN-LAST:event_jTFfiltrarLibroKeyReleased

    private void jTlistaAutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTlistaAutoresMouseClicked
        if(this.jTPlibro.getSelectedIndex() == 0 && this.jTFtituloLibro.isEditable()){
            int fila = this.jTlistaAutores.getSelectedRow();
            String idAutor = tablaAutor.getValueAt(fila, 0).toString();
            String nombreAutor = tablaAutor.getValueAt(fila, 1).toString();
            String fechaNacimientoAutor = tablaAutor.getValueAt(fila, 2).toString();
            
            this.jTFidAutor.setText(idAutor);
            this.jTFnombreAutor.setText(nombreAutor);
            
            try {
                fecha = formatoFecha.parse(fechaNacimientoAutor);
            } catch (ParseException ex) {
                Logger.getLogger(JFLibroSinIDyAnioPetado.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDCfechaNacimientoAutor.setDate(fecha);
            
            this.jTFidAutor.setEditable(false);
            this.jTFnombreAutor.setEditable(false);
            this.jDCfechaNacimientoAutor.setEnabled(false);
        }
    }//GEN-LAST:event_jTlistaAutoresMouseClicked

    private void jBactualizarDatosLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactualizarDatosLibroActionPerformed
        String idLibro = this.JTFidLibroModificar.getText();
        String tituloActualizado = this.jTFtituloLibroModificar.getText();
        String fechaActualizada = this.formatoFecha.format(this.jDCfechaPublicacionLibroModificar.getDate());
        String stockActualizado = this.jTFstockLibroModificar.getText();
        
        if(tituloActualizado.isEmpty() || stockActualizado.isEmpty() || this.jDCfechaPublicacionLibroModificar.getDate() == null){
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos antes de actualizar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro de actualizar?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(opcion == JOptionPane.YES_OPTION) {
                this.consulta.actualizarLibro(cn, idLibro, tituloActualizado, fechaActualizada, stockActualizado);
                // Actualiza la tabla después de la operación de actualización en la base de datos
                this.metodoTabla.actualizarTablaLibro(cn, tablaLibro);
                // Establece el modelo actualizado en la tabla
                this.jTlistalibros.setModel(tablaLibro); 
                // Limpia los campos y realiza otras acciones necesarias
                this.jTFfiltrarLibro.setText("");
                this.limpiarCeldasRegistrar();
            }
        }
    }//GEN-LAST:event_jBactualizarDatosLibroActionPerformed

    private void jBnuevoModificarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoModificarLibroActionPerformed
        this.BGfiltrar.clearSelection();
        this.JTFidLibroModificar.setText("");
        this.jTFtituloLibroModificar.setText("");
        this.jTFidAutorModificar.setText("");
        this.jDCfechaPublicacionLibroModificar.setDate(null);
        this.jTFstockLibro.setText("");
        this.jTFfiltrarLibro.setText("");
        this.metodoTabla.actualizarTablaLibro(cn, tablaLibro);
        this.jTlistalibros.setModel(tablaLibro);
    }//GEN-LAST:event_jBnuevoModificarLibroActionPerformed
 
    private void jBeliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarLibroActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "Esta Seguro de eliminar el Libro...?","Eliminar Libro", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(opcion == JOptionPane.YES_OPTION){
            String idLibro = this.JTFidLibroModificar.getText();
            
            this.consulta.eliminarLibro(cn, idLibro);
            this.metodoTabla.actualizarTablaLibro(cn, tablaLibro);
            this.jTlistalibros.setModel(tablaLibro);
            
            this.JTFidLibroModificar.setText("");
            this.jTFtituloLibroModificar.setText("");
            this.jTFidAutorModificar.setText("");
            this.jDCfechaPublicacionLibroModificar.setDate(null);
            this.jTFstockLibroModificar.setText("");
            this.BGfiltrar.clearSelection();
            this.jTFfiltrarLibro.setText("");
            this.limpiarCeldasRegistrar();
        }
    }//GEN-LAST:event_jBeliminarLibroActionPerformed

    private void jMnuvolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuvolverAlMenuActionPerformed
        jfMenu = new JFMenu();
        jfMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMnuvolverAlMenuActionPerformed

    private void jMnusalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnusalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMnusalirActionPerformed

    private void jTlistalibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTlistalibrosMouseClicked
        if(this.jTPlibro.getSelectedIndex() == 1){
            int fila = this.jTlistalibros.getSelectedRow();
            String idLibro = tablaLibro.getValueAt(fila, 0).toString();
            String titulo = tablaLibro.getValueAt(fila, 1).toString();
            String idAutor = tablaLibro.getValueAt(fila, 2).toString();
            String fechaPublicacion = tablaLibro.getValueAt(fila, 3).toString();
            String stock = tablaLibro.getValueAt(fila, 4).toString();

            this.JTFidLibroModificar.setText(idLibro);
            this.jTFtituloLibroModificar.setText(titulo);
            this.jTFidAutorModificar.setText(idAutor);
            try {
                fecha = formatoFecha.parse(fechaPublicacion);
            } catch (ParseException ex) {
                Logger.getLogger(JFLibroSinIDyAnioPetado.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDCfechaPublicacionLibroModificar.setDate(fecha);
            this.jTFstockLibroModificar.setText(stock);
        }
    }//GEN-LAST:event_jTlistalibrosMouseClicked

    private void jTFnombreAutorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnombreAutorKeyReleased
        this.metodoTabla.consultarAutor(cn, "NombreAutor", this.jTFnombreAutor.getText(), tablaAutor);
    }//GEN-LAST:event_jTFnombreAutorKeyReleased

    private void jTFidAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFidAutorKeyTyped
        char caracter = evt.getKeyChar(); 
        if(Character.isLetter(caracter)){ 
            evt.consume(); //ya no lo va a usar y borra el caracter 
            JOptionPane.showMessageDialog(null, "Ingrese solamente números.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
        }  
    }//GEN-LAST:event_jTFidAutorKeyTyped

    private void jTFnombreAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnombreAutorKeyTyped
        char caracter = evt.getKeyChar(); 
        if(Character.isDigit(caracter)){ 
            evt.consume(); //ya no lo va a usar y borra el caracter 
            JOptionPane.showMessageDialog(null, "Ingrese solamente letras.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
        }  
    }//GEN-LAST:event_jTFnombreAutorKeyTyped

    private void jTFstockLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFstockLibroKeyTyped
        char caracter = evt.getKeyChar(); 
        if(Character.isLetter(caracter)){ 
            evt.consume(); //ya no lo va a usar y borra el caracter 
            JOptionPane.showMessageDialog(null, "Ingrese solamente números.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
        }         
    }//GEN-LAST:event_jTFstockLibroKeyTyped

    private void jTFfiltrarLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFfiltrarLibroKeyTyped
        if(this.jRBidLibro.isSelected()){
            char caracter = evt.getKeyChar(); 
            if(Character.isLetter(caracter)){ 
                evt.consume(); //ya no lo va a usar y borra el caracter 
                JOptionPane.showMessageDialog(null, "Ingrese solamente números.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
            } 
        }
        else if(this.jRBtituloLibro.isSelected()){
            char caracter = evt.getKeyChar(); 
            if(Character.isDigit(caracter)){ 
                evt.consume(); //ya no lo va a usar y borra el caracter 
                JOptionPane.showMessageDialog(null, "Ingrese solamente letras.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
            }            
        }
    }//GEN-LAST:event_jTFfiltrarLibroKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLibroSinIDyAnioPetado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLibroSinIDyAnioPetado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLibroSinIDyAnioPetado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLibroSinIDyAnioPetado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLibroSinIDyAnioPetado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGfiltrar;
    private javax.swing.JTextField JTFidLibroModificar;
    private javax.swing.JButton jBactualizarDatosLibro;
    private javax.swing.JButton jBeliminarLibro;
    private javax.swing.JButton jBnuevoModificarLibro;
    private javax.swing.JButton jBnuevoRegistrarLibro;
    private javax.swing.JButton jBregistrarLibro;
    private com.toedter.calendar.JDateChooser jDCanioPublicacionLibro;
    private com.toedter.calendar.JDateChooser jDCfechaNacimientoAutor;
    private com.toedter.calendar.JDateChooser jDCfechaPublicacionLibroModificar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnusalir;
    private javax.swing.JMenuItem jMnuvolverAlMenu;
    private javax.swing.JPanel jPAutores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRBidLibro;
    private javax.swing.JRadioButton jRBtituloLibro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFfiltrarLibro;
    private javax.swing.JTextField jTFidAutor;
    private javax.swing.JTextField jTFidAutorModificar;
    private javax.swing.JTextField jTFnombreAutor;
    private javax.swing.JTextField jTFstockLibro;
    private javax.swing.JTextField jTFstockLibroModificar;
    private javax.swing.JTextField jTFtituloLibro;
    private javax.swing.JTextField jTFtituloLibroModificar;
    private javax.swing.JTabbedPane jTPlibro;
    private javax.swing.JTable jTlistaAutores;
    private javax.swing.JTable jTlistalibros;
    // End of variables declaration//GEN-END:variables
}
