package Vista;

import Conectar.ConexionBaseDatos;
import Negocio.ConsultaBaseDatos;
import Negocio.Tabla;
import java.awt.Image;
import java.awt.Toolkit;
//import Negocio.ConsultaMySQL;
import java.sql.Connection;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
//import java.time.LocalDate;
//import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer123
 */
public class JFPrestamoNoReal extends javax.swing.JFrame {

    ConexionBaseDatos con = new ConexionBaseDatos();
    Connection cn;
    ConsultaBaseDatos consulta;
    Tabla metodoTabla;
    DefaultTableModel tablaLibro, tablaEstudiante, tablaPrestamo;
    JFMenu jfMenu;
    SimpleDateFormat formatoFecha;
    Date fecha;
    
    public JFPrestamoNoReal() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            cn = con.conexion();
        } catch (SQLException ex) {
            Logger.getLogger(JFPrestamoNoReal.class.getName()).log(Level.SEVERE, null, ex);
        }
        consulta = new ConsultaBaseDatos();
        tablaLibro = (DefaultTableModel) this.jTlistalibros.getModel();
        tablaPrestamo = (DefaultTableModel) this.jTlistaPrestamos.getModel();
        tablaEstudiante = (DefaultTableModel) this.jTlistaEstudiantes.getModel();
        metodoTabla = new Tabla();
        this.metodoTabla.actualizarTablaLibro(cn, tablaLibro);
        this.metodoTabla.actualizarTablaEstudiante(cn, tablaEstudiante);
        this.metodoTabla.actualizarTablaPrestamo(cn, tablaPrestamo);
        BGfiltrar.add(jRBidLibro);
        BGfiltrar.add(jRBtituloLibro);
        this.JTFidPrestamoModificar.setEditable(false);
        this.jTFnombreEstudianteModificar.setEditable(false);
        this.jTFtituloModificar.setEditable(false);
        this.jDCfechaPrestamoModificar.setEnabled(false);
        this.limpiarCeldasRegistrar();
        this.jDCfechaNacimientoEstudiante.setEnabled(true);
        formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
    }

    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/LibroIcon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGfiltrar = new javax.swing.ButtonGroup();
        jTPPrestamo = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFtituloLibro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFstockLibro = new javax.swing.JTextField();
        jDCfechaPublicacionLibro = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jTFidLibro = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jBregistrarLibro = new javax.swing.JButton();
        jBnuevoRegistrarLibro = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTFidEstudiante = new javax.swing.JTextField();
        jTFnombreEstudiante = new javax.swing.JTextField();
        jDCfechaNacimientoEstudiante = new com.toedter.calendar.JDateChooser();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jDCfechaPrestamo = new com.toedter.calendar.JDateChooser();
        jDCfechaRetorno = new com.toedter.calendar.JDateChooser();
        jTFCantidad = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jRBidLibro = new javax.swing.JRadioButton();
        jRBtituloLibro = new javax.swing.JRadioButton();
        jTFfiltrarPrestamo = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTFidPrestamoModificar = new javax.swing.JTextField();
        jTFnombreEstudianteModificar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFcantidadModificar = new javax.swing.JTextField();
        jDCfechaPrestamoModificar = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jTFtituloModificar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jDCfechaRetornoPrestamoModificar = new com.toedter.calendar.JDateChooser();
        jPanel9 = new javax.swing.JPanel();
        jBactualizarDatosLibro = new javax.swing.JButton();
        jBeliminarLibro = new javax.swing.JButton();
        jBnuevoModificarLibro = new javax.swing.JButton();
        jBdevolucion = new javax.swing.JButton();
        jPEstudiantes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTlistaEstudiantes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTlistalibros = new javax.swing.JTable();
        jPListaPrestamos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTlistaPrestamos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnuvolverAlMenu = new javax.swing.JMenuItem();
        jMnusalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libros");
        setIconImage(getIconImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Libro"));

        jLabel2.setText("Título:");

        jLabel3.setText("Fecha de Publicación:");

        jTFtituloLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFtituloLibroKeyReleased(evt);
            }
        });

        jLabel7.setText("Stock:");

        jTFstockLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFstockLibroKeyTyped(evt);
            }
        });

        jDCfechaPublicacionLibro.setDateFormatString("yyyy-MM-dd");

        jLabel1.setText("ID Libro;");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTFstockLibro)
                        .addComponent(jDCfechaPublicacionLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(jTFtituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFidLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFidLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFtituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDCfechaPublicacionLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFstockLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBregistrarLibro.setText("Registrar Prestamo");
        jBregistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarLibroActionPerformed(evt);
            }
        });

        jBnuevoRegistrarLibro.setText("Agregar un Nuevo Prestamo");
        jBnuevoRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoRegistrarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jBregistrarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jBnuevoRegistrarLibro)
                .addGap(24, 24, 24))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBregistrarLibro)
                    .addComponent(jBnuevoRegistrarLibro))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Estudiante"));

        jLabel12.setText("ID Estudiante");

        jLabel13.setText("Nombre y Apellido:");

        jLabel14.setText("Fecha de Nacimiento:");

        jTFidEstudiante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFidEstudianteKeyTyped(evt);
            }
        });

        jTFnombreEstudiante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFnombreEstudianteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFnombreEstudianteKeyTyped(evt);
            }
        });

        jDCfechaNacimientoEstudiante.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFidEstudiante)
                    .addComponent(jTFnombreEstudiante)
                    .addComponent(jDCfechaNacimientoEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTFidEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTFnombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jDCfechaNacimientoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Daros del Prestamo"));

        jLabel11.setText("Fecha de Prestamo:");

        jLabel15.setText("Fecha de Retorno:");

        jLabel16.setText("Cantidad de Libros:");

        jDCfechaPrestamo.setDateFormatString("yyyy-MM-dd");

        jDCfechaRetorno.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jDCfechaPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDCfechaRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jTFCantidad))))
                .addGap(23, 23, 23))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jDCfechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jDCfechaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel16))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTFCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(8, 8, 8))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTPPrestamo.addTab("Registrar Libro", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar"));

        jRBidLibro.setText("ID Libro");

        jRBtituloLibro.setText("Título");

        jTFfiltrarPrestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFfiltrarPrestamoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFfiltrarPrestamoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jRBidLibro)
                .addGap(23, 23, 23)
                .addComponent(jRBtituloLibro)
                .addGap(18, 18, 18)
                .addComponent(jTFfiltrarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBidLibro)
                    .addComponent(jRBtituloLibro)
                    .addComponent(jTFfiltrarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevos Datos"));

        jLabel4.setText("ID Prestamo:");

        jLabel5.setText("Nombre de Estudiante:");

        jLabel6.setText("Fecha de Prestamo:");

        jLabel8.setText("Cantidad");

        jDCfechaPrestamoModificar.setDateFormatString("yyyy-MM-dd");

        jLabel9.setText("Titulo:");

        jLabel10.setText("Fecha de Retorno:");

        jDCfechaRetornoPrestamoModificar.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDCfechaRetornoPrestamoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFcantidadModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDCfechaPrestamoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFtituloModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFidPrestamoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFnombreEstudianteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFidPrestamoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTFtituloModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFnombreEstudianteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jDCfechaPrestamoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDCfechaRetornoPrestamoModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTFcantidadModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBactualizarDatosLibro.setText("Actualizar Datos");
        jBactualizarDatosLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarDatosLibroActionPerformed(evt);
            }
        });

        jBeliminarLibro.setText("Eliminar Libro");
        jBeliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarLibroActionPerformed(evt);
            }
        });

        jBnuevoModificarLibro.setText("Nuevo");
        jBnuevoModificarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoModificarLibroActionPerformed(evt);
            }
        });

        jBdevolucion.setText("Devolucion");
        jBdevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdevolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jBactualizarDatosLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBnuevoModificarLibro))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jBeliminarLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBdevolucion)))
                .addGap(25, 25, 25))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBactualizarDatosLibro)
                    .addComponent(jBnuevoModificarLibro))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBeliminarLibro)
                    .addComponent(jBdevolucion))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jTPPrestamo.addTab("Devolucion de Prestamo", jPanel2);

        jPEstudiantes.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Estudiantes"));

        jTlistaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idEstudiante", "NombreEstudiante", "FechaNacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTlistaEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTlistaEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTlistaEstudiantes);

        javax.swing.GroupLayout jPEstudiantesLayout = new javax.swing.GroupLayout(jPEstudiantes);
        jPEstudiantes.setLayout(jPEstudiantesLayout);
        jPEstudiantesLayout.setHorizontalGroup(
            jPEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEstudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPEstudiantesLayout.setVerticalGroup(
            jPEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEstudiantesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Libros"));

        jTlistalibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idLibro", "Titulo", "idAutor", "FechaPublicacion", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTlistalibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTlistalibrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTlistalibros);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );

        jPListaPrestamos.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Prestamos"));

        jTlistaPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPrestamo", "NombreEstudiante", "Titulo", "FechaPrestamo", "FechaRetorno", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTlistaPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTlistaPrestamosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTlistaPrestamos);

        javax.swing.GroupLayout jPListaPrestamosLayout = new javax.swing.GroupLayout(jPListaPrestamos);
        jPListaPrestamos.setLayout(jPListaPrestamosLayout);
        jPListaPrestamosLayout.setHorizontalGroup(
            jPListaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPListaPrestamosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPListaPrestamosLayout.setVerticalGroup(
            jPListaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMnuvolverAlMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuvolverAlMenu.setText("Volver al Menú");
        jMnuvolverAlMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuvolverAlMenuActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuvolverAlMenu);

        jMnusalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMnusalir.setText("Salir");
        jMnusalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnusalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMnusalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTPPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPListaPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 614, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 139, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTPPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPListaPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    private void jBregistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarLibroActionPerformed
        String idEstudiante = this.jTFidEstudiante.getText();
        String nombreEstudiante = this.jTFnombreEstudiante.getText();
        String fechaNacimientoEstudiante = "";

        String titulo = this.jTFtituloLibro.getText();
        String stock = this.jTFstockLibro.getText();
        
        String fechaPrestamo = "";
        String fechaRetorno = "";
        String cantidad = this.jTFCantidad.getText();
        

        String fechaPublicacion = "";
        if (this.jDCfechaNacimientoEstudiante.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fecha de nacimiento válida.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (this.jDCfechaPublicacionLibro.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fecha de publicación válida.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            fechaNacimientoEstudiante = this.formatoFecha.format(this.jDCfechaNacimientoEstudiante.getDate());
            fechaPublicacion = this.formatoFecha.format(this.jDCfechaPublicacionLibro.getDate());
            fechaPrestamo = this.formatoFecha.format(jDCfechaPrestamo.getDate());
            fechaRetorno = this.formatoFecha.format(jDCfechaRetorno.getDate());
        }

        if (idEstudiante.isEmpty() || nombreEstudiante.isEmpty() || titulo.isEmpty() || stock.isEmpty() ||
                this.jDCfechaNacimientoEstudiante.getDate() == null || this.jDCfechaPublicacionLibro.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor, corrige los campos antes de registrar.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (this.consulta.registrarPrestamo(cn, nombreEstudiante, titulo, fechaPrestamo, fechaRetorno, cantidad, idEstudiante, fechaNacimientoEstudiante,fechaPublicacion,stock)) {
                this.limpiarCeldasRegistrar();
                this.jTFnombreEstudiante.requestFocus();
            } else {
                this.metodoTabla.actualizarTablaPrestamo(cn, tablaPrestamo);
                this.metodoTabla.actualizarTablaLibro(cn, tablaLibro);
                this.metodoTabla.actualizarTablaEstudiante(cn, tablaEstudiante);
                this.jTlistaPrestamos.setModel(tablaPrestamo);
                this.jTlistalibros.setModel(tablaLibro);
                this.jTlistaEstudiantes.setModel(tablaEstudiante);
                this.jTFidEstudiante.setEditable(false);
                this.jTFnombreEstudiante.setEditable(false);
                this.jDCfechaNacimientoEstudiante.setEnabled(false);
                this.jTFtituloLibro.setEditable(false);
                this.jDCfechaPublicacionLibro.setEnabled(false);
                this.jTFstockLibro.setEditable(false);
            }
        }
    }//GEN-LAST:event_jBregistrarLibroActionPerformed

    private void jBnuevoRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoRegistrarLibroActionPerformed
        this.limpiarCeldasRegistrar();
        this.jTFnombreEstudiante.requestFocus();
        this.metodoTabla.actualizarTablaPrestamo(cn, tablaPrestamo);
        this.metodoTabla.actualizarTablaLibro(cn, tablaLibro);
        this.jTlistaPrestamos.setModel(tablaPrestamo);
        this.jTlistalibros.setModel(tablaLibro);
    }//GEN-LAST:event_jBnuevoRegistrarLibroActionPerformed

    private void limpiarCeldasRegistrar(){
        this.jTFidEstudiante.setEditable(true);
        this.jTFnombreEstudiante.setEditable(true);
        this.jDCfechaNacimientoEstudiante.setEnabled(true);
        this.jTFidLibro.setEditable(true);
        this.jTFtituloLibro.setEditable(true);
        this.jDCfechaPublicacionLibro.setEnabled(true);
        this.jTFstockLibro.setEditable(true);
        this.jTFidEstudiante.setText("");
        this.jTFnombreEstudiante.setText("");
        this.jDCfechaNacimientoEstudiante.setDate(null);
        this.jTFidLibro.setText("");
        this.jTFtituloLibro.setText("");
        this.jDCfechaPublicacionLibro.setDate(null);
        this.jTFstockLibro.setText("");
    }
    
    private void jTFfiltrarPrestamoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFfiltrarPrestamoKeyReleased
        if(this.jRBidLibro.isSelected()){
            this.metodoTabla.consultarLibro(cn, "idLibro", this.jTFfiltrarPrestamo.getText(), tablaLibro);
        }
        else if(this.jRBtituloLibro.isSelected()){
            this.metodoTabla.consultarLibro(cn, "Titulo", this.jTFfiltrarPrestamo.getText(), tablaLibro);

        }
        else{
            JOptionPane.showMessageDialog(null, "Elija un atributo para filtrar.", "Error", JOptionPane.ERROR_MESSAGE);
            this.jTFfiltrarPrestamo.setText("");
        }   
    }//GEN-LAST:event_jTFfiltrarPrestamoKeyReleased

    private void jBactualizarDatosLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactualizarDatosLibroActionPerformed
        String idPrestamo = this.JTFidPrestamoModificar.getText();
        String tituloActualizado = this.jTFtituloModificar.getText();
        String nombreEstudiante = this.jTFnombreEstudianteModificar.getText();
        String fechaPrestamo = this.formatoFecha.format(this.jDCfechaPrestamoModificar.getDate());
        String fechaRetorno = this.formatoFecha.format(this.jDCfechaRetornoPrestamoModificar.getDate());
        String cantidadActualizado = this.jTFcantidadModificar.getText();
        
        if(tituloActualizado.isEmpty() || cantidadActualizado.isEmpty() || this.jDCfechaPrestamoModificar.getDate() == null){
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos antes de actualizar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro de actualizar?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(opcion == JOptionPane.YES_OPTION) {
                this.consulta.actualizarPrestamo(cn, idPrestamo, tituloActualizado,nombreEstudiante, fechaPrestamo,fechaRetorno, cantidadActualizado);
                
                // Actualiza la tabla después de la operación de actualización en la base de datos
                this.metodoTabla.actualizarTablaPrestamo(cn, tablaPrestamo);
                this.metodoTabla.actualizarTablaLibro(cn, tablaLibro);
                // Establece el modelo actualizado en la tabla
                this.jTlistaPrestamos.setModel(tablaPrestamo); 
                // Limpia los campos y realiza otras acciones necesarias
                this.jTFfiltrarPrestamo.setText("");
                this.limpiarCeldasRegistrar();
            }
        }
    }//GEN-LAST:event_jBactualizarDatosLibroActionPerformed

    private void jBnuevoModificarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoModificarLibroActionPerformed
        this.BGfiltrar.clearSelection();
        this.JTFidPrestamoModificar.setText("");
        this.jTFnombreEstudianteModificar.setText("");
        this.jTFtituloModificar.setText("");
        this.jDCfechaPrestamoModificar.setDate(null);
        this.jDCfechaRetornoPrestamoModificar.setDate(null);
        this.jTFcantidadModificar.setText("");
        this.jTFfiltrarPrestamo.setText("");
        this.metodoTabla.actualizarTablaPrestamo(cn, tablaPrestamo);
        this.jTlistalibros.setModel(tablaLibro);
    }//GEN-LAST:event_jBnuevoModificarLibroActionPerformed
 
    private void jBeliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarLibroActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "Esta Seguro de eliminar el Prestamo...?","Eliminar Prestamo", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(opcion == JOptionPane.YES_OPTION){
            String idPrestamo = this.JTFidPrestamoModificar.getText();
            
            this.consulta.eliminarPrestamo(cn, idPrestamo);
            this.metodoTabla.actualizarTablaPrestamo(cn, tablaPrestamo);
            this.jTlistaPrestamos.setModel(tablaPrestamo);
            this.metodoTabla.actualizarTablaLibro(cn, tablaLibro);
            
            this.JTFidPrestamoModificar.setText("");
            this.jTFnombreEstudianteModificar.setText("");
            this.jTFtituloModificar.setText("");
            this.jDCfechaPrestamoModificar.setDate(null);
            this.jDCfechaRetornoPrestamoModificar.setDate(null);
            this.jTFcantidadModificar.setText("");
            this.BGfiltrar.clearSelection();
            this.jTFfiltrarPrestamo.setText("");
            this.limpiarCeldasRegistrar();
        }
    }//GEN-LAST:event_jBeliminarLibroActionPerformed

    private void jMnuvolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuvolverAlMenuActionPerformed
        jfMenu = new JFMenu();
        jfMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMnuvolverAlMenuActionPerformed

    private void jMnusalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnusalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMnusalirActionPerformed

    private void jTlistalibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTlistalibrosMouseClicked
        if(this.jTPPrestamo.getSelectedIndex() == 0 && this.jTFtituloLibro.isEditable()){
            this.jTFidLibro.setEditable(false);
            int fila = this.jTlistalibros.getSelectedRow();
            String idLibro = tablaLibro.getValueAt(fila, 0).toString();
            String titulo = tablaLibro.getValueAt(fila, 1).toString();
            String fechaPublicacion = tablaLibro.getValueAt(fila, 3).toString();
            String stock = tablaLibro.getValueAt(fila, 4).toString();

            this.jTFidLibro.setText(idLibro);
            this.jTFtituloLibro.setText(titulo);
            this.jTFstockLibro.setText(stock);
            
            try {
                fecha = formatoFecha.parse(fechaPublicacion);
            } catch (ParseException ex) {
                Logger.getLogger(JFPrestamoNoReal.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDCfechaPublicacionLibro.setDate(fecha);
            this.jTFstockLibro.setText(stock);
        }
        this.jTFtituloLibro.setEditable(false);
        this.jTFstockLibro.setEditable(false);
        this.jDCfechaPublicacionLibro.setEnabled(false);
    }//GEN-LAST:event_jTlistalibrosMouseClicked

    private void jTFnombreEstudianteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnombreEstudianteKeyReleased
        this.metodoTabla.consultarEstudiante(cn, "NombreEstudiante", this.jTFnombreEstudiante.getText(), tablaEstudiante);
    }//GEN-LAST:event_jTFnombreEstudianteKeyReleased

    private void jTFidEstudianteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFidEstudianteKeyTyped
        char caracter = evt.getKeyChar(); 
        if(Character.isLetter(caracter)){ 
            evt.consume(); //ya no lo va a usar y borra el caracter 
            JOptionPane.showMessageDialog(null, "Ingrese solamente números.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
        }  
    }//GEN-LAST:event_jTFidEstudianteKeyTyped

    private void jTFnombreEstudianteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnombreEstudianteKeyTyped
        char caracter = evt.getKeyChar(); 
        if(Character.isDigit(caracter)){ 
            evt.consume(); //ya no lo va a usar y borra el caracter 
            JOptionPane.showMessageDialog(null, "Ingrese solamente letras.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
        }  
    }//GEN-LAST:event_jTFnombreEstudianteKeyTyped

    private void jTFstockLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFstockLibroKeyTyped
        char caracter = evt.getKeyChar(); 
        if(Character.isLetter(caracter)){ 
            evt.consume(); //ya no lo va a usar y borra el caracter 
            JOptionPane.showMessageDialog(null, "Ingrese solamente números.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
        }         
    }//GEN-LAST:event_jTFstockLibroKeyTyped

    private void jTFfiltrarPrestamoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFfiltrarPrestamoKeyTyped
        if(this.jRBidLibro.isSelected()){
            char caracter = evt.getKeyChar(); 
            if(Character.isLetter(caracter)){ 
                evt.consume(); //ya no lo va a usar y borra el caracter 
                JOptionPane.showMessageDialog(null, "Ingrese solamente números.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
            } 
        }
        else if(this.jRBtituloLibro.isSelected()){
            char caracter = evt.getKeyChar(); 
            if(Character.isDigit(caracter)){ 
                evt.consume(); //ya no lo va a usar y borra el caracter 
                JOptionPane.showMessageDialog(null, "Ingrese solamente letras.","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
            }            
        }
    }//GEN-LAST:event_jTFfiltrarPrestamoKeyTyped

    private void jTlistaPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTlistaPrestamosMouseClicked
        if(this.jTPPrestamo.getSelectedIndex() == 1){
            int fila = this.jTlistaPrestamos.getSelectedRow();
            String idPrestamo = tablaPrestamo.getValueAt(fila, 0).toString();
            String nombreEstudiante = tablaPrestamo.getValueAt(fila, 1).toString();
            String titulo = tablaPrestamo.getValueAt(fila, 2).toString();
            String fechaPrestamo = tablaPrestamo.getValueAt(fila, 3).toString();
            String fechaRetorno = tablaPrestamo.getValueAt(fila, 4).toString();
            String cantidad = tablaPrestamo.getValueAt(fila, 5).toString();

            
            this.JTFidPrestamoModificar.setText(idPrestamo);
            this.jTFnombreEstudianteModificar.setText(nombreEstudiante);
            this.jTFtituloModificar.setText(titulo);
            this.jTFcantidadModificar.setText(cantidad);
            
            try {
                fecha = formatoFecha.parse(fechaPrestamo);
                fecha = formatoFecha.parse(fechaRetorno);
            } catch (ParseException ex) {
                Logger.getLogger(JFPrestamoNoReal.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDCfechaPrestamoModificar.setDate(fecha);
            this.jDCfechaRetornoPrestamoModificar.setDate(fecha);
        }
        
    }//GEN-LAST:event_jTlistaPrestamosMouseClicked

    private void jTlistaEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTlistaEstudiantesMouseClicked
        if(this.jTPPrestamo.getSelectedIndex() == 0 && this.jTFnombreEstudiante.isEditable()){
            int fila = this.jTlistaEstudiantes.getSelectedRow();
            String idEstudiante = tablaEstudiante.getValueAt(fila, 0).toString();
            String nombreEstudiante = tablaEstudiante.getValueAt(fila, 1).toString();
            String fechaNacimientoEstudiante = tablaEstudiante.getValueAt(fila, 2).toString();

            this.jTFidEstudiante.setText(idEstudiante);
            this.jTFnombreEstudiante.setText(nombreEstudiante);
            //            this.jTFfechaNacimientoEstudianteModificar.setText(fechaNacimiento);
            try {
                fecha = formatoFecha.parse(fechaNacimientoEstudiante);
            } catch (ParseException ex) {
                Logger.getLogger(JFEstudianteReal.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDCfechaNacimientoEstudiante.setDate(fecha);
        }
        
        this.jTFidEstudiante.setEditable(false);
        this.jTFnombreEstudiante.setEditable(false);
        this.jDCfechaNacimientoEstudiante.setEnabled(false);
    }//GEN-LAST:event_jTlistaEstudiantesMouseClicked

    private void jTFtituloLibroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFtituloLibroKeyReleased
        this.metodoTabla.consultarLibro(cn, "Titulo", this.jTFtituloLibro.getText(), tablaLibro);

    }//GEN-LAST:event_jTFtituloLibroKeyReleased

    private void jBdevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdevolucionActionPerformed
         // Obtener datos del préstamo seleccionado en la interfaz
            String idPrestamo = JTFidPrestamoModificar.getText();
            String nuevaFechaRetorno = formatoFecha.format(jDCfechaRetornoPrestamoModificar.getDate()); // Ajusta esto según la obtención de la fecha en tu interfaz
            String nuevaCantidad = jTFcantidadModificar.getText();
            

            // Llamar al método para realizar la devolución
            consulta.realizarDevolucion(cn, idPrestamo, nuevaFechaRetorno, nuevaCantidad);

            // Llamar a la función para eliminar el préstamo
            this.consulta.eliminarPrestamo(cn, idPrestamo);
            this.metodoTabla.actualizarTablaPrestamo(cn, tablaPrestamo);
            this.jTlistaPrestamos.setModel(tablaPrestamo);
            this.JTFidPrestamoModificar.setText("");
            this.jTFnombreEstudianteModificar.setText("");
            this.jTFtituloModificar.setText("");
            this.jDCfechaPrestamoModificar.setDate(null);
            this.jDCfechaRetornoPrestamoModificar.setDate(null);
            this.jTFcantidadModificar.setText("");
            this.BGfiltrar.clearSelection();
            this.jTFfiltrarPrestamo.setText("");
            this.limpiarCeldasRegistrar();

        // Realizar otras operaciones o actualizaciones en tu interfaz si es necesario
    }//GEN-LAST:event_jBdevolucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrestamoNoReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrestamoNoReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrestamoNoReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrestamoNoReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrestamoNoReal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGfiltrar;
    private javax.swing.JTextField JTFidPrestamoModificar;
    private javax.swing.JButton jBactualizarDatosLibro;
    private javax.swing.JButton jBdevolucion;
    private javax.swing.JButton jBeliminarLibro;
    private javax.swing.JButton jBnuevoModificarLibro;
    private javax.swing.JButton jBnuevoRegistrarLibro;
    private javax.swing.JButton jBregistrarLibro;
    private com.toedter.calendar.JDateChooser jDCfechaNacimientoEstudiante;
    private com.toedter.calendar.JDateChooser jDCfechaPrestamo;
    private com.toedter.calendar.JDateChooser jDCfechaPrestamoModificar;
    private com.toedter.calendar.JDateChooser jDCfechaPublicacionLibro;
    private com.toedter.calendar.JDateChooser jDCfechaRetorno;
    private com.toedter.calendar.JDateChooser jDCfechaRetornoPrestamoModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnusalir;
    private javax.swing.JMenuItem jMnuvolverAlMenu;
    private javax.swing.JPanel jPEstudiantes;
    private javax.swing.JPanel jPListaPrestamos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRBidLibro;
    private javax.swing.JRadioButton jRBtituloLibro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTextField jTFcantidadModificar;
    private javax.swing.JTextField jTFfiltrarPrestamo;
    private javax.swing.JTextField jTFidEstudiante;
    private javax.swing.JTextField jTFidLibro;
    private javax.swing.JTextField jTFnombreEstudiante;
    private javax.swing.JTextField jTFnombreEstudianteModificar;
    private javax.swing.JTextField jTFstockLibro;
    private javax.swing.JTextField jTFtituloLibro;
    private javax.swing.JTextField jTFtituloModificar;
    private javax.swing.JTabbedPane jTPPrestamo;
    private javax.swing.JTable jTlistaEstudiantes;
    private javax.swing.JTable jTlistaPrestamos;
    private javax.swing.JTable jTlistalibros;
    // End of variables declaration//GEN-END:variables
}
